### ISSUE TITLE
Symfony 3 Compatibility

### ISSUE THREAD

**Issue by patkar** [sulu/sulu#2106]
| Q | A |
| --- | --- |
| Bug? | no |
| Version Used | n/a |
| New Feature? | yes |

This is a meta issue to track progress of all the PRs here and in other packages for Symfony 3 compatibility.
#### Packages to update
- [x] `doctrine/doctrine-bundle: ^1.5.1`
- [x] `doctrine/doctrine-fixtures-bundle: ^2.3`
- [x] `doctrine/phpcr-bundle: ^1.3` -> #2013, #2125 
- [x] `friendsofsymfony/http-cache: t.b.d.`
- [x] `gedmo/doctrine-extensions: t.b.d.`
- [x] `guzzle/guzzle` -> `guzzlehttp/guzzle: ^6.0` (no symfony deps anymore) -> https://github.com/sulu/sulu/pull/3070
- [x] `liip/theme-bundle: ^1.4` -> https://github.com/sulu/SuluThemeBundle/pull/5
- [x] `massive/build-bundle: t.b.d.` -> https://github.com/massiveart/MassiveBuildBundle/pull/12 https://github.com/massiveart/MassiveBuildBundle/pull/13
- [x] `massive/search-bundle: t.b.d.`
- [x] `matthiasnoback/symfony-dependency-injection-test: ^0.7.6` -> #2105 
  - [x] `matthiasnoback/symfony-config-test: ^1.3.1` -> #2105 
- [x] `phpcr/phpcr-shell: t.b.d.`
- [x] `pulse00/ffmpeg-bundle: ^0.6` -> #2114 
- [x] `stof/doctrine-extensions-bundle: ^1.2.2`
- [x] `sulu/document-manager: t.b.d.` -> https://github.com/sulu/sulu-document-manager/pull/103
  - [x] `symfony-cmf/core-bundle: t.b.d.` -> removed this dependency
- [ ] `symfony-cmf/routing: ^2.0` (will be released end of 2016)
- [ ] `symfony-cmf/routing-bundle: 2.0` (will be released end of 2016)
- [x] `symfony/monolog-bundle: ^2.8.2`
- [x] `willdurand/hateoas-bundle: ^1.1` -> https://github.com/sulu/sulu/pull/3071
  - [x] `willdurand/hateoas: ^2.9`
  - [x] `jms/serializer-bundle: ^1.1`
#### Packages which need a compatibility PR itself
- [x] `friendsofsymfony/http-cache`: Since `^1.4.1` it's compatible to Symfony 3 on it's own, but still requiring `guzzle/guzzle: ~3.8`
- [x] `gedmo/doctrine-extensions` (only require-dev dependency)
- [x] `massive/build-bundle` ->  massiveart/MassiveBuildBundle#12 massiveart/MassiveBuildBundle#13
- [x] `massive/search-bundle` -> massiveart/MassiveSearchBundle#83
- [x] `phpcr/phpcr-shell`
- [x] `dantleech/phpcr-migrations-bundle` -> dantleech/phpcr-migrations-bundle#8
- [x] `sulu/document-manager` -> https://github.com/sulu/sulu-document-manager/pull/103
  - [x] `symfony-cmf/core-bundle` -> symfony-cmf/CoreBundle#181
- [ ] `symfony-cmf/routing-bundle` -> symfony-cmf/RoutingBundle#333
  - [x] sonata-project/SonataDoctrinePhpcrAdminBundle#363
#### Sulu bundles without deprecation notices
- [ ] `AdminBundle`
- [ ] `CategoryBundle`
- [ ] `CollaborationBundle`
- [ ] `ContactBundle`
- [ ] `ContentBundle`
- [x] `CoreBundle` -> #2743 
- [x] `DocumentManagerBundle` -> #2720 
- [x] `GeneratorBundle` -> #2721
- [ ] `HashBundle`
- [x] `HttpCacheBundle` -> #2722 
- [x] `LocationBundle`
- [x] `MarkupBundle` -> #2723
- [ ] `MediaBundle`
- [x] `PersistenceBundle` -> #2725
- [x] `PreviewBundle` -> #2726
- [ ] `ResourceBundle`
- [x] `RouteBundle` -> #2727
- [ ] `SearchBundle`
- [ ] `SecurityBundle`
- [ ] `SnippetBundle`
- [ ] `TagBundle`
- [ ] `TestBundle`
- [x] `TranslateBundle` -> #2737 
- [ ] `WebsiteBundle`
- [x] `WebsocketBundle` -> #2728
#### Other steps
- [x] Modify test runner to fail on bundles which have already no deprecation notices, to prevent the introduction of new ones. -> #2120, #2369, #2745
- [x] Add Symfony 3 to Travis matrix with allow failures (if deps are met and installable).
- [ ] Fix possible remaining errors and arm Symfony 3 tests.
- [ ] Do the full update to Symfony 3 only (routing, etc.) -> maybe directly after a new minor release?

**Comment by chirimoya** [comment]
@patkar ... thanks for your effort!

**Comment by alexander-schranz** [comment]
:+1:

**Comment by webmozart** [comment]
Thanks a lot for working on this @patkar! :)

**Comment by danrot** [comment]
Merged #2125, and therefore ticked the element in the list.

**Comment by patkar** [comment]
@danrot So sorry I didn't get any time to finish it (:

**Comment by danrot** [comment]
@patkar Not a big deal, most of the remaining stuff was other libraries anyway...
