### ISSUE TITLE
Cleanup after React rewrite is finished

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3435]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | dev-develop
| Browser Version | ---

#### Actual Behavior

Currently we are adding new features for the new react-based admin while trying to keep the old admin working.

#### Expected Behavior

The old legacy code should be removed once we finished the rewrite. This issue will be used as a todo list, which describes all the legacy code we are currently keeping.

- [x] Remove the old code in all `Resources/public/js` directories (#4046)
- [x] Remove the rules for the old code in [`.eslintignore`] (https://github.com/sulu/sulu/blob/38df05e/.eslintignore#L4) (#4046)
- [x] Replace the [`indexAction`](https://github.com/sulu/sulu/blob/38df05e57bacd7b99f6632096153635b75d4ac26/src/Sulu/Bundle/AdminBundle/Controller/AdminController.php#L156) with the new `indexV2Action` and fixe the Symfony routes accordingly (including all other routes being prefixed with `v2`) (#4045)
- [x] Rename `getNavigationV2` occurences to `getNavigation` (#4045)
- [x] Remove all the `getFields` actions (#4045)
- [x] Remove our `AuthenticationHandler` (#4045)
- [ ] Remove the `JSConfig` services (?)
- [x] Remove `ContentNavigation` services (#4045)
- [x] Remove obsolete routes (#4045)
- [ ] Remove unnecessary methods from `ContentTypeInterface` (`getDefaultValue`? `getDefaultParams`?)
- [x] Remove `Widget` classes from AdminBundle (#4045)
- [ ] Remove current behat files and contexts
- [x] (Re)move old translations (#4043)
- [x] Remove old SCSS (#4046)
- [x] Remove old bower and package.json files (#4046)
- [x] Remove gruntfiles (#4046)
- [x] Remove TranslateBundle (#4043)
- [x] ~~~Remove TextEditor Config on server side~~~ -> Do not remove, but maybe extract into separate bundle? (Might need further discussion)
- [x] Remove `TemplateController` (#4045)
- [ ] Remove `fields_account_medias` and `fields_contact_medias` actions
- [ ] Think about how to handle `getTemplate` from `RuleTypeInterface`
- [ ] Fix AudienceTargetingBundle
