### ISSUE TITLE
PHP 8.0 Roadmap

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5646]
# Problem description

Wanted to have a look what would be needed to support PHP 8. At current state I must sadly tell it will not be possible without big effort to support sulu 1.6 and php 8.0 the first packages I checked with conflichts is the [DoctrineCacheBundle](https://github.com/doctrine/DoctrineCacheBundle) and [Puls00FFmpegBundle](https://github.com/pulse00/ffmpeg-bundle) both are abandoned and so will not merge any pull requests.

So I would think when not specially requested by a sponsor or partner we will focus PHP 8 support for the 2.x (current 2.1) Version.

# Proposed solution

## Conflicting packages

From the `composer why php` list:

 - [x] doctrine/orm (coming soon: https://twitter.com/beberlei/status/1329338553407578112)
 - [x] handcraftedinthealps/rest-routing-bundle https://github.com/handcraftedinthealps/RestRoutingBundle/pull/8
 - [x] handcraftedinthealps/zendsearch https://github.com/handcraftedinthealps/ZendSearch/pull/3
 - [x] friendsofsymfony/http-cache
 - [x] friendsofsymfony/http-cache-bundle
 - [x] friendsofsymfony/jsrouting-bundle
 - [x] symfony-cmf/slugifier-api https://github.com/symfony-cmf/slugifier-api/pull/6
 - [x] symfony-cmf/routing-bundle (only github actions: https://github.com/symfony-cmf/routing-bundle/pull/459)
    - [x] symfony/testing https://github.com/symfony-cmf/Testing/pull/208
 - [x] doctrine/phpcr-bundle https://github.com/doctrine/DoctrinePHPCRBundle/pull/355
 - [x] jackalope/jackalope-doctrine-dbal (only github actions https://github.com/jackalope/jackalope-doctrine-dbal/pull/378)
 - [x] jackalope/jackrabbit (only github actions https://github.com/jackalope/jackalope-jackrabbit/pull/165)
 - [x] phpcr/phpcr-migrations (https://github.com/phpcr/phpcr-migrations/pull/12)
   - [x] jackalope/jackalope-fs https://github.com/jackalope/jackalope-fs/pull/28
 - [x] league/flysystem-azure-blob-storage (doesnt conflict but need to be checked if works as has >=5.6 in it) https://github.com/sulu/sulu/pull/5751
 - [x] toflar/psr6-symfony-http-cache-store (needs update to 3.0 https://github.com/sulu/sulu/pull/5750) 
 - [x] phpcr/phpcr-shell https://github.com/phpcr/phpcr-shell/pull/209
 - [x] php-ffmpeg/php-ffmpeg (needs update to https://github.com/sulu/sulu/pull/5755)
 - [x] oro/doctrine-extensions (doesn't conflict but need to be checked if it works as  has >= 5.4 and no release since 2019) #5752
 - [x] matamo/device-detector #5643
      - [-] mustangostang/spyc (will be updated with #5643)
 - [x] layershifter/tld-database (will be removed in #5754)
 - [x] layershifter/tld-extract (will be removed in #5754)
 - [x] layershifter/tld-support (doesn't conflict but need to be checked as has >= 5.5 in it)  (will be removed in #5754)
 - [x] jms/serializer-bundle
 - [x] jms/serializer
 - [x] jms/metadata
 - [x] goodby/csv (need to be checked as >= 5.3) (hope it works because no release and no accepted PR since 2017)
 - [x] gedmo/doctrine-extensions (needs to be checked as >= 5.3) #5753
    - [-] behat/transliterator 
 - [x] JMS Serializer https://github.com/schmittjoh/JMSSerializerBundle/pull/830
 - [x] doctrine/* packages Upgrade https://github.com/sulu/sulu/pull/5774
 - [x] ~~php-http/guzzle6-adapter https://github.com/php-http/guzzle6-adapter/pull/86~~ Requirement removed in: https://github.com/sulu/sulu/pull/5811
 - [x] stof/doctrine-extensions-bundle replaced with antishov/doctrine-extensions-bundle https://github.com/sulu/sulu/pull/5814
 - [x] rokka-io/imagine-vips https://github.com/rokka-io/imagine-vips/pull/17 (requires release)
 - [x] Prepare PHP 8 compatibility https://github.com/sulu/sulu/pull/5813
 - [x] Add PHP 8 compatibility https://github.com/sulu/sulu/pull/5757
 
 The following should work but are not tested yet with PHP 8:
 
 - [ ] imagine/imagine (need to be checked as >= 5.3) https://github.com/avalanche123/Imagine/pull/758
 - [ ] superbalist/flysystem-google-storage (doesnt conflict but need to be checked if works as has >=5.5 and no release since 2019) https://github.com/Superbalist/flysystem-google-cloud-storage/pull/119
     - [-] google/cloud-core (same)
 - [ ] league/flysystem-aws-s3-v3 (need to be checked) https://github.com/thephpleague/flysystem-aws-s3-v3/pull/238
      - [-] aws/aws-sdk-php

 ## Check compatibility of the bundles:
 
  - [x] https://github.com/sulu/web-twig/pull/32
  - [x] https://github.com/sulu/SuluAutomationBundle/pull/48
  - [x] https://github.com/sulu/SuluFormBundle/pull/280
  - [x] https://github.com/sulu/SuluCommunityBundle/pull/141
  - [x] https://github.com/sulu/SuluRedirectBundle/pull/62
  - [x] https://github.com/sulu/SuluHeadlessBundle/pull/72
  - [x] https://github.com/sulu/SuluContentBundle/pull/187
  - [x] https://github.com/sulu/SuluArticleBundle/pull/546
      - [x] handcraftedinthealps/elasticsearch-dsl
      - [x] handcraftedinthealps/elasticsearch-bundle

## Known Issues

The following issues are not blocking but need to be keep in mind before upgrading a project to PHP 8:

 - [ ] https://github.com/doctrine/migrations/issues/1104 (Problems with transactions) (Workaround: using isTransactional false)
     - [ ] https://github.com/doctrine/dbal/pull/4481
 - [ ] https://github.com/Imagick/imagick/issues/358 (No PHP 8 release yet) (Workaround: Compiling Imagick yourself or use GD or Vips adapter)
 - [ ] https://github.com/deployphp/deployer/commit/042d1006906002ef580e5453894c4fd47180701e (No stable PHP 8 release yet)

**Comment by goetas** [comment]
JMS Serializer with php 8 support has been released :)

**Comment by chirimoya** [comment]
> JMS Serializer with php 8 support has been released :)

Thanks!

**Comment by alexander-schranz** [comment]
I updated the Issue Description with a section called **Known Issues**, this issues do not effect sulu itself but should be keep in mind before using PHP 8 for a Project.

**Comment by alexander-schranz** [comment]
We finally [merged](https://github.com/sulu/sulu/pull/5757) the PHP 8 support of sulu core, the most used bundles and did upgrade some other php packages to support PHP 8. 🎉 

![](https://media.giphy.com/media/sRFym5lssgcTFrMSac/giphy.gif)

The support will be released with the release of the bundles and the next patch release of 2.1 and 2.2 Version of sulu.
