### ISSUE TITLE
Permission are not removed when Page or Collection is deleted

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6344]
| Q | A
| --- | ---
| Sulu Version | 2.4@dev

# Actual Behavior

Permission are not removed when Page or Collection is deleted.

# Expected Behavior

The permission of a page should also be deleted and being able to be restored when a trash item is restored.

# Steps to Reproduce

A: Page

1. Create a Page
2. Give the Page Permissions
3. Save it
4. Delete it

Still an entry in the `se_access_control` is there.

B: Collection

1. Create a Collection
2. Give the Collection Permissions
3. Save it
4. Delete it

Still an entry in the `se_access_control` is there.

# Possible Solutions

Remove permission with a Document and Entity Listener.
Store and Restore of the specific entity need to handle permissions.

# TODO 

- [ ] Remove Permissions or remove
- [ ] Store Permissions in Trash
- [ ] Restore Permissions on restore

**Comment by luca-rath** [comment]
We cannot remove the permissions easily after deletion, because the `ActivityController` and the `TrashItemController` both check the permissions

**Comment by mamazu** [comment]
Probably also related to the new Storage backend. #7672 Could be solved with the new structure as well.
