### ISSUE TITLE
Missing things for Copy & Paste Functionality of Blocks

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6638]
There are some tests missing for the BlockCollection Copy Functionality from the following Pull Request: https://github.com/sulu/sulu/pull/6630

The functionality of the `BlockCollection.js` should be covered by tests. This should be target before the 2.5 release.

## TODO List

 - [x] Test functionality in BlockCollection.test.js
 - [x] Add Docs for Clipboard specially how to use it with mobx reaction invoke immediatly as example
 - [ ] We can currently not paste or add a block on the top?

**Comment by niklasnatter** [comment]
Related issue: https://github.com/sulu/sulu/issues/6436
