### ISSUE TITLE
Ideas about integrating AI support into Sulu

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7046]
# Problem description

This issue is about collecting ideas about how we could use AI in a beneficial way to improve the user experience and assist the content management.

# Ideas

 - [ ] Toolbar Action with assist prompt chat
 - [ ] Image Description/Alt Tag generation
 - [ ] SEO Description / Tags generation
 - [ ] Create Summary of pages ([comment](https://github.com/sulu/sulu/issues/7046#issuecomment-1490196430))
 - [ ] Sample Content Generation for devs ([comment](https://github.com/sulu/sulu/issues/7046#issuecomment-1490202065))
 - [ ] Feeding AI with own Content to let Users ask questions ([comment](https://github.com/sulu/sulu/issues/7046#issuecomment-1490305519))
 - [ ] Changing existing content with AI ([https://www.olexdsgn.com/figgpt](https://www.olexdsgn.com/figgpt))

# Technical Challanges

The 4000 Token limit and no availability of sessions in current state of Open AI.

**Comment by wachterjohannes** [comment]
@alexander-schranz another idea would be to have a shortcut which opens a "conversation" and feed the model with data from the database. which would enable the user to do something like this:

```
Use the content from page `/case-studies/allianz` and create a summary for the overview page.
```

The output would then be displayed n the conversation.

**Comment by sanderquirynen** [comment]
Generate sample data.

It would be handy during development of we could quickly generate sample content.
How this could work:
1. Similar to clicking the 'add page' button, you click 'generate sample pages'
2. You get a prompt to select an existing page to base the data on and how many items you want to generate
3. Pages are generated in the same directory, with the same template and blocks as the selected base-page
5. An extra feature could be to enter a topic for each generated page, otherwise the base-page is used to base content off
6. Text is automatically generated, images could be fetched from Pexels or the likes, or generated with another AI

**Comment by d3vpunk** [comment]
Feeding an AI with the content of a whole webspace and make prompt / chat available on the homepage.
Example prompt: "What are the opening times of the shop on tuesday?" 
Example output: "Tuesday from 09:00 - 20:00. Click <sulu page> for more information"

**Comment by alexander-schranz** [comment]
Some ideas we also can get from this figma plugin: https://www.olexdsgn.com/figgpt

**Comment by TheCadien** [comment]
A cool feature could be that you can tag a text_area or text_editor property in the form.xml, let's call it "tldr" with a reference to another text property and the feature generates in this 2nd property a "to long dindt read" summary of the 1st text field.

Would be great for teasers in blogs for example :D

**Comment by FlxRobole** [comment]
Hoping to assist you in this issue I introduce to you the [SuluAITranslatorBundle](https://github.com/robole-dev/sulu-ai-translator-bundle/) which allows translating fields or whole pages/snippets/forms via one-click in the user interface using DeepL API.

**Comment by nevercodealone** [comment]
FAQ generator.
