### ISSUE TITLE
Using Symfony tagged_iterator instead of compiler passes

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#7402]
# Problem description
Currently Sulu reimplements the [Symfony DI `tagged_iterator` functionality](https://gitlab.dev-b24.de/sylius/sylius/-/merge_requests/2094) for many services. While this is a good idea if you want to have custom logic, this makes no sense in this case. Affected services would be:
- [x] src/Sulu/Component/Symfony/CompilerPass/TaggedServiceCollectorCompilerPass.php (#7424)
- [x] MarkupBundle/DependencyInjection/CompilerPass/TagCompilerPass.php
- [x] MarkupBundle/DependencyInjection/CompilerPass/ParserCompilerPass.php (#7403)
- [x] RouteBundle/DependencyInjection/RouteGeneratorCompilerPass.php
- [x] MediaBundle/DependencyInjection/FormatCacheClearerCompilerPass.php (#8037)
- [x] AdminBundle/DependencyInjection/Compiler/AddAdminPass.php (#8034)
- [x] MediaBundle/DependencyInjection/ImageTransformationCompilerPass.php (#8306)
- [x] PageBundle/DependencyInjection/Compiler/StructureExtensionCompilerPass.php
- [x] CoreBundle/DependencyInjection/Compiler/RegisterContentTypesCompilerPass.php
- [x] AdminBundle/DependencyInjection/Compiler/AddMetadataProviderPass.php (#8038 )
- [x] AudienceTargetingBundle/DependencyInjection/Compiler/AddRulesPass.php (#7405)
- [x] ~DocumentManagerBundle/DependencyInjection/Compiler/InitializerPass.php (#7724)~
- [x] PageBundle/DependencyInjection/Compiler/SmartContentDataProviderCompilerPass.php
- [x] CoreBundle/DependencyInjection/Compiler/ListBuilderMetadataProviderCompilerPass.php
- [x] SecurityBundle/DependencyInjection/Compiler/AccessControlProviderPass.php (#8039 )
- [x] CoreBundle/DependencyInjection/Compiler/RegisterLocalizationProvidersPass.php (#8035)

# Proposed solution
Use the constructor and call the function from there or make it immutable. So that you can't add services dynamically.

# Future ideas
Maybe in the future we could replace this tagging logic with attributes like this:
```php

#[AsLocalizationProvider]
class CustomLocalizationProvider {}
```

**Comment by alexander-schranz** [comment]
Would nice if you can extend the issue with a list of services and its releated tags were the `Tagged_iterator` make sense to discuss if we go with `constructor` injections or calling the `add` method.

**Comment by mamazu** [comment]
Updated it.

**Comment by mamazu** [comment]
Oddly enough the `ListBuilderMetadataProviderCompilerPass` configures a service that no longer exists.
