### ISSUE TITLE
Migrate rest routings to default symfony routing files

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7434]
# Problem description

We want to remove the https://github.com/handcraftedinthealps/RestRoutingBundle as preperation for removing FOSRest.

The first step which we can already do on `2.6` is redefine all our routes in a new routing file `yaml` instead of the old `yml` and document that project should switch already to the new routing files.

https://github.com/sulu/skeleton/blob/2.6/config/routes/sulu_admin.yaml

# Proposed solution

Skeleton: `config/routes/sulu_admin.yaml`:

```diff
sulu_tag_api:
-    resource: "@SuluTagBundle/Resources/config/routing_api.yml"
-    type: rest
+    resource: "@SuluTagBundle/Resources/config/routing_api.yaml"
     prefix: /admin/api
```

Sulu: `src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yml` (keep as it is on 2.6) (remove on 3.0):

```yaml
sulu_tag.tags:
    type: rest
    name_prefix: sulu_tag.
    resource: sulu_tag.tag_controller

sulu_tag.post_tag_merge:
    path: /tags/merge.{_format}
    methods: POST
    defaults:
        _controller: sulu_tag.tag_controller::postMergeAction
        _format: json
```

Sulu: `src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml` (add to 2.6):

```yaml
sulu_tag.get_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::getAction
    methods: GET
    format: json
    requirements:
       _format: json|csv

sulu_tag.get_tags:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::cgetAction
    methods: GET
    format: json
    requirements:
        _format: json|csv

sulu_tag.post_tag:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::postAction
    methods: POST
    format: json
    requirements:
        _format: json|csv

sulu_tag.put_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::putAction
    methods: PUT
    format: json
    requirements:
        _format: json|csv

sulu_tag.delete_tag:
    path: /tags/{id}.{_format}
    controller: sulu_tag.tag_controller::deleteAction
    methods: DELETE
    format: json
    requirements:
        _format: json|csv

sulu_tag.patch_tags:
    path: /tags.{_format}
    controller: sulu_tag.tag_controller::cpatchAction
    methods: PATCH
    format: json
    requirements:
        _format: json|csv

sulu_tag.post_tag_merge:
    path: /tags/merge.{_format}
    controller: sulu_tag.tag_controller::postMergeAction
    methods: POST
    format: json
    requirements:
        _format: json|csv
```

When changing from `yml` to `yaml` the output of the both routing should be nearly similar when running  `bin/console debug:router --format json`.

# TODO

 - [x] AdminBundle https://github.com/sulu/sulu/pull/7512
 - [x] ActivityBundle https://github.com/sulu/sulu/pull/7515
 - [x] AudienceTargetingBundle https://github.com/sulu/sulu/pull/8009
 - [x] CategoryBundle https://github.com/sulu/sulu/pull/8005
 - [x] ContactBundle https://github.com/sulu/sulu/pull/8001
 - [x] CoreBundle https://github.com/sulu/sulu/pull/8007
 - [x] CustomUrlsBundle https://github.com/sulu/sulu/pull/8003
 - [x] RouteBundle https://github.com/sulu/sulu/pull/8008
 - [x] MediaBundle https://github.com/sulu/sulu/pull/8004
 - [x] PageBundle https://github.com/sulu/sulu/pull/8003
 - [x] PreviewBundle https://github.com/sulu/sulu/pull/7526
 - [x] SecurityBundle https://github.com/sulu/sulu/pull/8002
 - [x] SearchBundle https://github.com/sulu/sulu/pull/7516
 - [x] SnippetBundle https://github.com/sulu/sulu/pull/8006
 - [x] TagBundle https://github.com/sulu/sulu/pull/7511
 - [x] TrashBundle https://github.com/sulu/sulu/pull/7514
 - [x] ReferenceBundle https://github.com/sulu/sulu/pull/7513
 - [x] WebsiteBundle https://github.com/sulu/sulu/pull/8003

None rest routes to yaml:

 - [x] AdminBundle
 - [x] LocationBundle
 - [x] MediaBundle
 - [x] WebsiteBundle

None core bundles:

 - [x] sulu/SuluFormBundle
 - [x] sulu/SuluCommentBundle
 - [x] sulu/SuluRedirectBundle
 - [x] sulu/SuluContentBundle
 - [x] sulu/SuluArticleBundle
 - [x] sulu/SuluHeadlessBundle
 - [x] sulu/SuluSyliusConsumerBundle
 - [x] sulu/SuluSyliusProducerPlugin
 - [x] sulu/SuluAutomationBundle
 - [x] sulu/SuluCommunityBundle

Todo:

 - [ ] Check SecuredControllerInterface functionality without Rest Routing

**Comment by mario-fehr** [comment]
@alexander-schranz do we keep the prefix `/admin/api` in the `config/routes/sulu_admin.yaml`?
In your examples above you mixing it for example `path: /admin/api/tags/{id}.{_format}` and `/tags/merge.{_format}`

**Comment by alexander-schranz** [comment]
@mario-fehr Yes, currently no bc breaks planned.

**Comment by mario-fehr** [comment]
@alexander-schranz whats more preferred a PR per Bundle or multiple (all) Bundles in one PR?

**Comment by TheCadien** [comment]
@mario-fehr It's best to make individual ones :) 
I just started making a few out of boredom at the airport, unfortunately I overlooked that you wrote something in here. 
But then everyone can grab a few :)

**Comment by mamazu** [comment]
Maybe it would make sense to write a script seeing that users might also need to migrate their routes from the bundle to the flat strucutre.

**Comment by alexander-schranz** [comment]
The migration path should now be quiet easier with the new command created by @mamazu https://github.com/handcraftedinthealps/RestRoutingBundle

```
bin/console fos:rest:routing:dump-symfony-routes
```

Steps for upgrade.

1. Install the Bundle
2. Register routes
3. Run e.g.: `bin/console fos:rest:routing:dump-symfony-routes --controller=sulu_tag.tag_controller`
4. Create a `.yaml` files, replace `.yml` with `.yaml`
5. Reformat dump routes

Format to match this output:

```diff
-sulu_tag.tags:
-    type: rest
-    name_prefix: sulu_tag.
-    resource: sulu_tag.tag_controller

+sulu_tag.get_tag:
+    path: /tags/{id}.{_format}
+    controller: sulu_tag.tag_controller::getAction
+    methods: GET
+    format: json
+    requirements:
+       _format: json|csv
```

we migrated all of the core bundles. If somebody want to create the new routing files for the additoinal bundles (articles, form, community, ...) it would be nice.

All bundles even not using rest rout should have a `.yaml` routing file if routing is required. In 3.0 we will then remove the old .yml or even .xml files.

**Comment by alexander-schranz** [comment]
@TheCadien if you want to tackle this.

**Comment by mamazu** [comment]
@alexander-schranz The HeadlessBundle is done. (It doesn't have any routes)

**Comment by mamazu** [comment]
Do we also want to migrate the ContentBundle as this will be part of Sulu 3 anyways?

**Comment by mamazu** [comment]
SyliusConsumerBundle and SyliusProducerBundle do not have any routes.

**Comment by alexander-schranz** [comment]
Can somebody validate which bundles where already updated and which one not?

**Comment by mamazu** [comment]
## The current state of the removal:
- [x] sulu/SuluFormBundle
- [x] sulu/SuluCommentBundle
- [x] sulu/SuluRedirectBundle
- [x] sulu/SuluContentBundle (only in some test code)
- [x] sulu/SuluArticleBundle
- [x] sulu/SuluHeadlessBundle
- [x] sulu/SuluSyliusConsumerBundle
- [x] sulu/SuluSyliusProducerPlugin
- [x] sulu/SuluAutomationBundle
- [x] sulu/SuluCommunityBundle

**Comment by alexander-schranz** [comment]
Thank you all we can finally close this one 🎉
