### ISSUE TITLE
Excerpt for Internal or External Link Pages

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7473]
# Problem description

When have a internal or external link page it should be possible still to define Excerpt Data. This way the content manager can still control data representing a teaser to that page. Additional it is even easier to add External pages to smart content, example a external news entry and still categorize or tag it.

# Proposed solution

Allow to define excerpt data even when page is from type internal or external.

# TODO

Check for BC Breaks:

 - [x] Check which data is currently used by the navigation twig extension for external / internal pages
      - ✅  External Pages: Own Excerpt is loaded
      - ❌  Internal Pages: Target Excerpt is loaded (BC Break ⚠️) (This actually would be @datenwerk-at)
 - [ ] Check which data is currently used for page_selection content type for external / internal pages
 - [ ] Check which data is currently used for smart content content type for external / internal pages

**Comment by datenwerk-at** [comment]
@alexander-schranz In the main purpose of the internal link pages feature it is fine that the target excerpt for navigation twig is used. But sometimes you need as special excerpt. Is it possible to add next to "Link title" also a optional field for "Description" that overrules the target page excerpt?

![grafik](https://github.com/sulu/sulu/assets/82949579/ae50a69a-7a8d-47d9-8710-90d7d083dedb)
