### ISSUE TITLE
Remove deprecated code for version Sulu version 3

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#7547]
| Q | A
| --- | ---
| Sulu Version | 3.0
| PHP Version | -
| DB Version | -
| Browser Version | -

For version 3 we should clean up the structure to actually remove stuff that's deprecated.

## Todos

- [x] Remove KernelBrowser (#7718)
- [x] Remove User Salt functionality (waits for #7743)
- [x] Remove Symfony BC layer (https://github.com/sulu/sulu/pull/7743)
- [x] `DeprecatedCompilerPass` should have been removed in 2.0
    - [x] #7721 (for removing Symfony 7.2 deprecations)
    - [x] #7424 
    - [x] #7405
    - [x] #7403 
- [x] `BreadcrumbItemInterface`
- [x] `TokenAlreadyRequestedException.php`
- [ ] Deprecated function in the `TabViewBuilderTrait`
- [x] `Sulu/Bundle/WebsiteBundle/Twig/Core/UtilTwigExtension::extract`
- [x] `Sulu/Bundle/WebsiteBundle/Twig/Meta/MetaTwigExtension`
- [x] `Sulu/Bundle/WebsiteBundle/Controller/WebsiteController::getRequest`
- [x]  `Sulu/Bundle/WebsiteBundle/Controller/RedirectController::redirectWebspaceAction`
- [ ] `Sulu\Bundle\MediaBundle\Media\ImageConverter\Transformation\CropTransformation`
- [x] `Container Parameter 'sulu_media.media.max_file_size'` (https://github.com/sulu/sulu/pull/7766)
- [ ] ContactBundle `Account::notes`
- [x] SecurityBundle `Permission::module`
- [ ] `Sulu/Bundle/ContactBundle/Controller/AbstractMediaController`
- [x] `ReturnTypeWillChange` add correct return type remove attribute (https://github.com/sulu/sulu/pull/8170)
- [ ] Migrate usage of `RequestParameterTrait` to `$request->get()` #7815 

### Js
- [x] securityContextStore.js
- [x] localizationStore.js `loadLocalizations`
- [ ] ToolbarActions have a lot of deprecated code in them
- [x] FullLoadingStrategy.js
- [x] webspaceStore.js (#7763)

**Comment by mamazu** [comment]
This is probably more something for 4.0 or something as we don't want to have too many BC breaks in this version (as the main focus is getting rid of phpcr)

**Comment by alexander-schranz** [comment]
Things which are deprecated can be removed aslong there is a real alternative provided.

Something like https://github.com/sulu/sulu/blob/e5cfa4d76104dabca227db25390b7b4aedd855e8/src/Sulu/Component/Cache/MemoizeInterface.php#L28 for example.

**Comment by mamazu** [comment]
Well there is a lot of things like that. But I can create pull requests for all of those.

**Comment by alexander-schranz** [comment]
>  ApiEntityWrapper / ApiEntity

We probably will not tackle this in 3.0 because of heavy BC Break.

> DefaultSnippetExtension

All deprecation in src/ Pages, Article, Snippet, Custom Url, Document Manager, PHPCR, Jackalope can be ignored this bundles will be rewritten to packages dir.

> SmartContent

Can be ignored will be also be rewritten.

> Sulu/Bundle/ContactBundle/Controller/AbstractMediaController

@mamazu what is here todo?

**Comment by mamazu** [comment]
In the AbstractMediaController some fields are null and this has a lot of deprecated code that can be removed when they're not optional.

**Comment by alexander-schranz** [comment]
I also added the `ReturnTypeWillChange` to the todo list eventually @opctim will target that as a split from: https://github.com/sulu/sulu/pull/7776 but added it here that we recheck it before the 3.0 release that we removed and updated all currently used `ReturnTypeWillChange`.

**Comment by mamazu** [comment]
About the `Sulu\Bundle\ContactBundle\Entity\Account::notes` array, the property is deprecated but the getter / setter aren't and they're still used in the AbstractContactManager. Should this really be removed?

**Comment by mamazu** [comment]
We should also consider replacing the TokenStorageInterface with the "new" Symfony security class:

## Before
```php
        private TokenStorageInterface $tokenStorage,
//....
        $token = $this->tokenStorage->getToken();
        if (!$token) {
            return;
        }

        $user = $token->getUser();
        if (!$user instanceof UserInterface) {
            return;
        }
```

## After
```php
        private Security $security,
//....
        $user = $this->security->getUser();
        if (!$user instanceof UserInterface) {
            return;
        }
```

**Comment by alexander-schranz** [comment]
> We should also consider replacing the TokenStorageInterface with the "new" Symfony security class:

Personally I would say no, Security class is like a AbstractController so just a wrapper around underlaying Symfony services. Where possible I would use the underlay service not a wrapper.

**Comment by mamazu** [comment]
Done. 🎉
