### ISSUE TITLE
CustomUrl without PHPCR

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7566]
# Problem description

Implementing a new CustomUrl entity which supports the same features as we currently have

 - Title
 - Published
 - Base Domain -> discussion if we introduce a key to make migration stage <-> prod easier
 - Url Parts (Custom Urls can support multiple *)
 - Full Url (maybe required for website routing)
 - Target page -> will be replaced by Link field type (articles also supported)
    - resourceKey
    - resourceId
 - Redirect (Yes or No)
 - Canonical URL (Yes or No)
 - No Index
 - No Follow

This will remove and replace the whole CustomUrlDocument and existing services.

# Proposed solution

Functionality should be the same.

## Todos

 - [ ] Create new Entity
 - [ ] Implement Admin Controller for Add, Edit, Delete Webspace Custom Url entities
 - [ ] Implement Website Routing
 - [ ] Migration in https://github.com/sulu/SuluPHPCRMigrationBundle for 2.6 -> 3.x upgrade check this with @Prokyonn

**Comment by mamazu** [comment]
PR can be found here: #7570

**Comment by mamazu** [comment]
This should be done now right?
