### ISSUE TITLE
New Content Storage Roadmap (Sulu-3.0) 🚀 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7672]
# When will Sulu 3.0 come

[Read more about on our Blog](https://sulu.io/blog/sulu-3-0-taking-a-bit-more-time-to-get-it-right)

# Problem description

Copy the not yet finished todo list out of https://github.com/sulu/sulu/pull/7611 and https://github.com/sulu/SuluContentBundle/pull/271 to keep tracking of it.

#### Selection Content Types

 - [x] ContentResolving https://github.com/sulu/sulu/pull/7611/commits/cff56651a99ec47ea552891c3c67fc392226107a
   - [x] Category
   - [x] Media 
 - [x] https://github.com/Prokyonn/sulu/pull/3
   - [x] Single Media
 - [x] https://github.com/Prokyonn/sulu/pull/4
   - [x] ImageMap
   - [x] Collection
   - [x] Single Collection
 - [x] https://github.com/Prokyonn/sulu/pull/1
   - [x] Account 
   - [x] Single Account
   - [x] Contact
   - [x] Single Contact
   - [x] Contact / Account
 - [x] https://github.com/Prokyonn/sulu/pull/2
    - [x] Tags
 - [x] Date https://github.com/sulu/sulu/pull/7729
 - [x] DateTime https://github.com/sulu/sulu/pull/7729
 - [x] Location (may not require own Resolver)
 - [x] SettingsResolver 
 - [x] ~~Snippet~~
 - [x] ~~Single Snippet~~
 - [x] ~~Page~~
 - [x] ~~Single Page~~

##### Inconsistencies

- [x] fix inconsistencies between ImageMapPropertyResolver and BlockProperty resolver regarding wrapping child objects in a ContenView or extracting it directly  #8092 
- [x] Create an additional interface for `MetadataAware` property resolvers, the `view` should only return scalar values, (e.g. metadata object must not be returned)    https://github.com/sulu/sulu/pull/8094
- [x] Blocks on `minOccurs="1" maxOccurs="1"` returns not a list: https://github.com/sulu/sulu/blob/418a50aaf9345e59c997b5ee2fdf4526bab72ec7/src/Sulu/Component/Content/Types/BlockContentType.php#L407-L409 Reported by @benr77 https://github.com/sulu/sulu/pull/7751  
- [x] Title limited to 64 chars we should atleast have 191 chars and set via a metadata visitor for content bundle based titles a frontend validation. Reported by @benr77: https://github.com/sulu/sulu/issues/7744. 
- [x] Seo Variables are inconsistent instead of `title` it is `seoTitle` same mostly for excerpt. Reported by @benr77  
- [x] Extensions inside `content.seo` instead of `extension.seo`. Reported by @benr77
- [ ] Recheck `request` parameter (we should move some to app.request.attributes to avoid duplication. Recommend usage of `app.locale` for get current localization and so on.  
- [x] Resolve settings:  https://github.com/sulu/sulu/pull/7774  
   - [x] Last Modified?

#### None Core

 - [x] Article
 - [ ] Form
 
#### Link Provider ( to be discussed ) -> ( discussed LinkLoader will call link providers )

 - [x] Media https://github.com/Prokyonn/SuluContentBundle/pull/1
 - [x] Page https://github.com/Prokyonn/SuluContentBundle/pull/1
 - [x] Article https://github.com/Prokyonn/SuluContentBundle/pull/1
 - [x] Update LinkProvider rename `getConfiguration` to `getConfigurationBuilder` to be consistent with the new implementation: https://github.com/sulu/sulu/pull/8176
 
#### Teaser Provider ( to be discussed ) -> ( discussed TeaserLoader will call teaser providers )

 - [x] Page https://github.com/Prokyonn/SuluContentBundle/pull/2
 - [x] Article https://github.com/Prokyonn/SuluContentBundle/pull/2

#### Bundles

- [x] Article Bundle
- [x] Snippet Bundle https://github.com/sulu/sulu/pull/7728
- [x] Page Bundle https://github.com/sulu/sulu/pull/7804
- [x] Custom Url Bundle https://github.com/sulu/sulu/pull/7570 @mamazu (@wachterjohannes please review the admin part, website routing we need tackle after removing old routing code)
  - [x] Admin Management (https://github.com/sulu/sulu/pull/7570)
  - [x] Routing (Website) @wachterjohannes  (https://github.com/sulu/sulu/pull/8247)
  - [ ] HttpCache

#### More todos

- [x] New Routing https://github.com/sulu/sulu/pull/7726
- [x] LastModified https://github.com/sulu/sulu/pull/7738
- [x] Build Command for Homepage https://github.com/sulu/sulu/pull/7818
- [x] Global Blocks https://github.com/sulu/sulu/pull/7826
- [x] Navigation Contexts https://github.com/sulu/sulu/pull/7839
- [x] Refactor ContentResolver to recursively resolve ResolvableResources with priority (e.g. selections first, media last)
- [x] Cleanup old code
   - [x] Services #7995
   - [x] Classes #8137
   - [x] Dependencies #8160

#### Alpha Versions

- [x] First Alpha 
 
#### Smart content

 - [x] Core Adoptions https://github.com/sulu/sulu/pull/8032
 - [x] Media https://github.com/sulu/sulu/pull/8032
 - [x] Contacts https://github.com/sulu/sulu/pull/8032
 - [x] Accounts https://github.com/sulu/sulu/pull/8032
 - [x] Pages https://github.com/sulu/sulu/pull/8032
 - [x] Snippets https://github.com/sulu/sulu/pull/8032
 - [x] Articles https://github.com/sulu/sulu/pull/8032
 - [x] Article Page Tree ( ArticledimensionContent.route.parent.resourceId = page.uuid )

#### BlockVisitors

- [x] HiddenBlockVisitor
- [x] ScheduleBlockVisitor
- [x] TargetGroupBlockVisitor (AudienceTargetingBundle)
- [x] SegmentBlockVisitor (PageBundle)

#### Other todos

- [x] Update JS tools for packages dir: https://github.com/sulu/sulu/pull/7808
- [x] Make Excerpt Extendable
- [x] Make Seo Extendable
- [ ] Make Settings Extendable
- [x] Implement a new controller for the `Show History` functionality in the admin and reenable the button again ([see](https://github.com/sulu/sulu/pull/7882/files)) https://github.com/sulu/sulu/pull/8270
- [x] Url Strategy for Pages Tree structure, tree full edit and leaf edit @alexander-schranz https://github.com/sulu/sulu/pull/8265
- [x] Route Schema handling (see comment [here](https://github.com/sulu/sulu/pull/8125#discussion_r2313576223))
- [ ] Route Conflict handling (see comment [here](https://github.com/sulu/sulu/pull/8125#discussion_r2313576528))
- [x] PathCleanup replacers for `&` and others (see comment [here](https://github.com/sulu/sulu/pull/8125#discussion_r2313613987)) https://github.com/sulu/sulu/pull/8181
- [x] Pathcleanup replacers recheck Umlauts (see pathcleanup in media tests [here](https://github.com/sulu/sulu/pull/8142/files)) https://github.com/sulu/sulu/pull/8181
- [x] Remove old replacers xml files as not longer needed
- [ ] Make [special character JS](https://github.com/sulu/sulu/blob/193f780b41da71a8be244cd3e4f3f79829f6c013/src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js#L32-L33) configurable to support CN, JP chars in urls 
- [x] Refresh Url with Parent not working with `route` in Edit (see also code [here](https://github.com/sulu/sulu/blob/9a9efeac6dbb5572b85b2140af52a55a2d2a4c01/src/Sulu/Bundle/PageBundle/Resources/js/index.js#L52-L54) which only handles resource_locator not route ) https://github.com/sulu/sulu/pull/8234
- [ ] Add [unique identifier (see issue)](https://github.com/sulu/sulu/issues/7846) for each block (FE + phpcr-migration) @TheCadien  (@wachterjohannes https://github.com/sulu/sulu/pull/8262)
  - [x] For new blocks https://github.com/sulu/sulu/pull/8262
  - [ ] phpcr-migration (https://github.com/sulu/SuluPHPCRMigrationBundle/pull/8)
- [x] Remove Page or Article does not remove routes
- [ ] Rename Route:site to Webspace or WebspaceKey
- [x] JSON Validation (see PropertyMetadataMapperInterface on content types)
- [x] Snippet Excerpt (own excerpt with less fields)
- [ ] Should Media Bundle Controller and Manager  depend on route bundle PathCleanup service
- [ ] Recheck Twig Extensions
- [x] Recheck sulu_content_load Twig Extension (sulu_page_load, sulu_article_load) https://github.com/sulu/sulu/pull/8246
- [x] Breadcrum twig extension (sulu_breadcrumb)
- [x] Navigation sulu_navigation_tree twig extension @Prokyonn https://github.com/sulu/sulu/pull/8250 
- [x] Recheck Selections params config @Prokyonn 
    - [x] Properties params resolve not all
- [x] Recheck Smart content params config @Prokyonn @alexander-schranz 
- [x] Recheck Selections types param 
- [x] Recheck Smart content types param 
- [x] Recheck Resolving of settings tab to twig @Prokyonn 
- [x] Recheck Resolving of block settings to twig @Prokyonn 
- [x] Recheck multilingual false handling
- [x] Recheck xi include works @martinlagler 
- [x] Reimplement [SuluCollector service](https://github.com/sulu/sulu/pull/8151) for 3.0 Content Bundle https://github.com/sulu/sulu/pull/8163
- [x] Recheck Preview Links @martinlagler 
- [x] Recheck Preview links noIndex SEO @martinlagler 
- [ ] Recheck readonly and final in new services (@Prokyonn, @alexander-schranz )
- [x] Remove Locale in Page, Article, Snippet https://github.com/sulu/sulu/pull/8277
- [x] Recheck Translation files as suggestion [here](https://github.com/sulu/sulu/pull/8136#discussion_r2318973253) by @Prokyonn 
- [x] Page Copy & Move ( https://github.com/sulu/sulu/issues/8022 ) https://github.com/sulu/sulu/pull/8046
- [ ] Remove ignored url on copied pages (https://github.com/sulu/sulu/pull/8046) as soon as the Route resolving of duplicates (e.g. -1 / -2) is added
- [x] DescendantProviderInterface for Content / Pages (access control manager)
- [ ] Recheck Slug length see https://github.com/sulu/sulu/issues/7980 Discuss @chirimoya
- [ ] Remove usage of FormMetadata::getName in JavaScript: https://github.com/sulu/sulu/pull/7984/files#r2122952242 
- [ ] Do not duplicate url in templateData, make route property name dynamic https://github.com/sulu/sulu/blob/5d6c0f218f56682fd5f2f658f0e6870dc2a38730/packages/content/src/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php#L73 @alexander-schranz 
- [ ] Check Route defaults provider where to get classes / repositories: https://github.com/sulu/sulu/blob/3.0/packages/content/src/Infrastructure/Sulu/Route/ContentRouteDefaultsProvider.php#L79-L84 
- [x] Page Link Type (previously internal external type) Now Link via link type
- [ ] Replacement for ParameterResolver / TemplateAttributeResolver ?
- [x] Main and Additonal Webspaces @wachterjohannes  https://github.com/sulu/sulu/pull/7992
- [x] Main and Additonal Webspaces for Sitemap Provider
- [x] Smart Contents @Prokyonn  https://github.com/sulu/sulu/pull/8032
- [ ] Teaser Provider over own Repository @Prokyonn @alexander-schranz 
- [x] Activity Functionality @draconivis 
   - [x] Page https://github.com/sulu/sulu/pull/8087
   - [x] Snippet https://github.com/sulu/sulu/pull/8107
   - [x] Article https://github.com/sulu/sulu/pull/8110
   - [x] CustomUrl
   - [x] SnippetArea https://github.com/sulu/sulu/pull/8260
- [x] Trash Functionality @Prokyonn 
- [ ] Find better place for Localization handling see [here](https://github.com/sulu/sulu/issues/8175)
- [x] Show ghost and shadow pages filter for pages
- [x] Shadow Badges in Page Tree, Article list or other views
- [x] Page Reorder / Sort in Tree View https://github.com/sulu/sulu/pull/7813
- [x] Pages Move in Tree View https://github.com/sulu/sulu/pull/8046
- [x] References Functionality https://github.com/sulu/sulu/pull/8122 @Prokyonn 
- [x] Areas / Default Snippets https://github.com/sulu/sulu/pull/7964 @mamazu
  - [x] PHPCR-Migration @wachterjohannes (https://github.com/sulu/SuluPHPCRMigrationBundle/pull/10)
- [x] Sitemap Provider @martinlagler 
   - [x] https://github.com/sulu/sulu/pull/8096
   - [x] https://github.com/sulu/sulu/pull/8174
- [ ] Sitemap Twig Extension (deprecate maybe in favor of navigation contexts)
- [x] Versioning Functionality https://github.com/sulu/sulu/pull/8054
- [x] Search integration https://github.com/sulu/sulu/pull/8186
- [x] Admin ReindexProviders
- [x] Website ReindexProviders
- [x] Permission Tab for Pages @draconivis
- [ ] Permission Migration old classes to new classes in access control tables
- [ ] Recheck Sulu Build command for search
- [ ] Recheck Sulu maintain command for search reindex
- [x] Add Transition Event eventually (see comment [here](https://github.com/sulu/sulu/pull/8087#discussion_r2274009511))
- [x] Article Types / Permissions
  - [x] Base and Permissions (https://github.com/sulu/sulu/pull/8124)
  - [x] Deep Route for a single article
  - [x] Type translations (https://github.com/sulu/sulu/pull/8124#discussion_r2400393771)
- [x] ContentController or request listener CacheLifeTime handling https://github.com/sulu/sulu/pull/8091 @alexander-schranz 
- [x] Cache Tags eventually maybe over Resolvable or References (to be discussed)
- [x] Cache Invalidation
- [x] Audience Targeting
  - [x] Core @wachterjohannes (https://github.com/sulu/sulu/pull/8085)
  - [x] PHPCR-Migration @wachterjohannes (https://github.com/sulu/SuluPHPCRMigrationBundle/pull/8) 
- [x] Segments
  - [x] Core @wachterjohannes (https://github.com/sulu/sulu/pull/8085)
  - [x] PHPCR-Migration @wachterjohannes  (https://github.com/sulu/SuluPHPCRMigrationBundle/pull/8) 
  - [x] Functional CachingTest see 2.6 [here](https://github.com/sulu/sulu/blob/99534f4a076fdf71a94ce9193fd8f4b38e99e143/src/Sulu/Bundle/WebsiteBundle/Tests/Functional/CachingTest.php#L68-L125) @wachterjohannes 
- [x] Reimplement [SecurityListenerTest](https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/WebsiteBundle/Tests/Functional/EventListener/SecurityListenerTest.php) for 3.0
- [x] Reimplement [SecurityListener](https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/WebsiteBundle/EventListener/SecurityListener.php) for 3.0
- [x] Reimplement [SecuritySubscriber](https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/SecurityBundle/Serializer/Subscriber/SecuritySubscriber.php) for 3.0
- [ ] Reimplement SecurityBehavior in ActivityRepository / ActivityRepositoryTest
- [x] Remove Structure, Structure Documents and Interfaces @alexander-schranz 
- [ ] ContentRichEntityRepository
- [ ] Xliff Export Import
- [ ] Content Architecture Naming
- [ ] Get correct webspace key in navigation twig extensions for internal links to other webspace: https://github.com/sulu/skeleton/pull/308
- [ ] SuluPHPCRMigrationBundle
    - [ ] Validate RouteMigration since latest changes in the new RouteBundle @wachterjohannes 
- [ ] Documentation
- [x] Update Crowdin Upload for including [new packages](https://github.com/sulu/sulu/blob/3.0/.github/workflows/crowdin-upload.yaml) @wachterjohannes  https://github.com/sulu/sulu/pull/8020, https://github.com/sulu/sulu/pull/8167
- [x] Remove eventually symfony/form requirement and so requirement to csrf protection package and config https://github.com/sulu/sulu/pull/8177
- [ ] Remove eventually `sulu.context` based service definitions
- [ ] Remove different behaviour based on `sulu.context` instead depend on firewall name or setting from request attributes.
- [ ] Remove `sulu.context` in bundles registration https://github.com/sulu/sulu/pull/8183
- [ ] Recheck auto set of authored / author (found in article-bundle where it was automaticly set)
- [x] Fix remove draft https://github.com/sulu/sulu/pull/8278
- [x] When adding a new locale, it can break the admin (Multiple homepages are displayed)
- [ ] Check if the IconSelection works with the DefaultPropertyResolver or if we need the create a specific one
- [ ] When you create a page in "DE" and then switch languages without language copy and error occurs on save
- [ ] Adjust the RouteGenerator to not depend on the RequestContext and the webspace (see https://github.com/sulu/sulu/pull/8122/files/690570253a297ccf57971f351b8d6037380d61e0#r2313184434)
- [ ] check `getResourceSecurityObjectType` for Activity Events (Page, Snippet & Article)
- [ ] Check support for _hash / user conflict handling
- [ ] Route changes Http Cache (invalidateTag fallback to invalidateRegex (old url), fallback to invalidateUrl)
- [ ] History Route remove Http Cache (invalidateUrl)
- [ ] Symfony Recipe
- [ ] Article Routing not match should not keep in mind
- [x] PageTreeRoutePropertyResolver
- [ ] Investigate deactivation of BlockVisitors for the "admin-context" as the content is partially resolved to write the References
- [x] Bug: When I only create an Article in `en` and switch to `de` in the overview the article occurs 2 times (Snippets, Articles, Pages)
- [x] ArticleBundle new features in 2.6:
  - Add new column/filter to article-controller sulu/SuluArticleBundle#722
  - Add content-fields to admin list search sulu/SuluArticleBundle#719

#### Security

The loaders may need to keep security in mind.

 - [x] Media Selection (currently handled by MediaManager)
 - [x] Single Media Selection (currently handled by MediaManager)
 - [x] Smart Content Media
 - [x] Page Selection
 - [x] Single Page Selection
 - [x] Smart Content Page
 - [x] SitemapProvider 

#### References (to be discussed)

- [x] Cache tags
- [x] ReferenceBundle

#### Optional

- [ ] Group / Type Switcher (optional)
- [ ] ONGR Article View Bundle (optional) https://github.com/sulu/SuluArticleViewDocumentBundle/pull/1 @wachterjohannes

**Comment by alexander-schranz** [comment]
Two things @benr77 stumbled over in the new content storage.

1. Global Blocks are not yet supported. Think there are two ways of implementing it.
   A. Implementing an own reusable service 
   B. Implement it as a block visitor (not sure if possible)
2. Blocks behave differently in the past `minOccurs="1" maxOccurs="1"` did change the output to twig to only return the single item e.g. `content.blocks.title` instead of `content.blocke.0.title`: https://github.com/sulu/sulu/blob/418a50aaf9345e59c997b5ee2fdf4526bab72ec7/src/Sulu/Component/Content/Types/BlockContentType.php#L407-L409. The same mechanic should may be readded to the new block propety resolver.

**Comment by mamazu** [comment]
I've tried upgrading a project to 3.0 and found that the new bundle doesn't yet have support for webspace settings yet (like what default snippets for what type should be used).

**Comment by alexander-schranz** [comment]
Default snippets / areas are in the list above.

**Comment by mamazu** [comment]
If there is already a plan for that, I could help with the implementation.

**Comment by alexander-schranz** [comment]
@mamazu sure the admin part can already be tackled controller should be easy inside the `packages/snippet/src/UserInterface/Controller/Admin` the API is based on the areaKey and webspaceKey not on the id itself look at the existing 2.6 calls:

 - `cgetAction` (list)
 - `putAction` with a `CreateOrModifySnippetAreaMessage`
 - `deleteAction` with a `RemoveSnippetAreaMessage`

The Domain / Model `SnippetArea` also:

 - `id` (auto increment)
 - `webspaceKey` (string not nullable)
 - `areaKey` (string not nullable)
 - `snippet` (relation) on-delete="cascade" not nullable

The compiler pass need to be copied to the new `Infrastructure/Symfony/DependencyInjection` location. https://github.com/sulu/sulu/blob/33e8b72844761ffc7483a3a95649445c0f48c424/src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php#L46-L51. The differerence between `2.6` and `3.0` is that now always the areas need to be defined not longer automatically creating areas per snippet type. So this lines https://github.com/sulu/sulu/blob/33e8b72844761ffc7483a3a95649445c0f48c424/src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php#L46-L51 and this: https://github.com/sulu/sulu/blob/33e8b72844761ffc7483a3a95649445c0f48c424/src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php#L69-L71 can be removed.

Create an own `SnippetAreaAdmin` class to add the snippet area tab.

**Comment by alexander-schranz** [comment]
@Prokyonn we need to recheck this deprecation:

![Image](https://github.com/user-attachments/assets/723d65b1-658a-4b0a-897d-0fac3243201a)

**Comment by mamazu** [comment]
@alexander-schranz  I created the Admin, the controller and the entity classes. However I don't yet get where the entity is being created and what the compiler pass is for.

**Comment by alexander-schranz** [comment]
@mamazu See https://sulu.rocks/admin/#/webspaces/demo/snippet-areas?locale=en compiler pass is which areas are shown.

**Comment by mamazu** [comment]
@alexander-schranz Do we have a replacement for the `MetadataFactory` already? I'm currently putting most of the the snippet area info into the response via Normalizer. I'm not sure that's the correct way to do it. see #7964

**Comment by alexander-schranz** [comment]
Lets discuss that in #7964

**Comment by mamazu** [comment]
I think this can be closed an unpinned from the most important issues as well now that Sulu is out?
